# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# stages -> stage -> jobs -> job -> steps -> step 

trigger:
- none

pool:
  vmImage: 'TestAgentPool'

variables:
   tag: $(Build.SourceVersion)

stages:
  - stage: Build and Deploy
    displayName: Build Stage
    jobs: 
    - job: Build
      displayName: Build Job
      pool: 'TestPoolAgent'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'svc-acrdevopsdemo01'
          repository: 'devops01/acrdevopsdemo01-app01'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      


