# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# stages -> stage -> jobs -> job -> steps -> step 

trigger:
- none

pool:
  vmImage: 'TestAgentPool'

variables:
   tag: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build Stage
    jobs: 
    - job: Build
      displayName: Build Job
      pool: 'TestAgentPool'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'svc-acrdevopsdemo01'
          repository: 'devops01/acrdevopsdemo01-app01'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(Build.BuildId)'
  

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactsDirectory)'
          OverWrite: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'kube-manifests'
          publishLocation: 'Container'
